config/routes.rb
Rails.application.routes.draw do
  get 'public/userranks'
  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 root to: 'public/homes#top'
 get 'about' => 'public/homes#about'

  scope module: :public do
  resources :posts, only: [:index, :edit, :new, :create, :destroy, :update] do
  resource :likes, only: [:create, :destroy]
end
  resources :users, only: [:show,:edit,:update]
  resources :ranks, only: [:index,]
  resources :myranks, only: [:index,]
  resources :charts, only: [:index]
  resources :completions, only: [:index]
  resources :completions2, only: [:index]
  resources :completions3, only: [:index]
  resources :completions4, only: [:index]
  resources :completions5, only: [:index]
  resources :completions6, only: [:index]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  enum evaluation: {worst:1, bad:2, nb:3, good:4, best:5}
  validates :body, presence: true
  validates :waste, presence: true
  validates :evaluation, presence: true

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  def liked_by?(user)
   likes.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no.user.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/myranks_helper.rb
module MyranksHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/userranks_helper.rb
module UserranksHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container-fluid pt-2 pb-2 bg-light'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>©さぼめも</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg shadow p-3 mb-5 bg-white rounded" style="background-color: ##FFEFD5	;">
    <div class="container">
      <a class="navbar-dark text-dark" href="/"><span><strong><h2 style="display:inline;">さぼめも</strong></h2>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-dark form-inline' do %>
            <h4 style="display:inline;">ま</h4>いぺーじ
            <% end %>
          </li>
          <li>
            <%=  link_to posts_path ,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">み</h4>んなのめも
            <% end %>
          </li>
          <li>
            <%=  link_to ranks_path ,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">ら</h4>んきんぐ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">ろ</h4>ぐあうと
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to about_path,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">さ</h4>ぼめもについて
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">と</h4>うろく
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-dark' do %>
            <h4 style="display:inline;">ろ</h4>ぐいん
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sabomemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP&display=swap" rel="stylesheet">
  </head>
  <body>
   <%= render "layouts/header" %>
   <main>
    <%= yield %>
   </main>
　 <%= render 'layouts/footer' %>
  </body>
</html>